var portofolio = [
	[
		'Website Pelayanan Laboratorium Teknik Informatika Universitas Gunadarma',
		'porto1.png',
		'porto1_1.png',
		'LabTI - Universitas Gunadarma, pengembangan sistem pelayanan berbasis web application. Sistem ini digunakan untuk memudahkan pelaporan praktikan yang berhalangan hadir saat praktikum berlangsung serta memudahkan staff laboratorium dalam pendataan praktikan yang berhalangan hadir.',
		'0',
		'Internal Application',
	],
	[
		'Katolik Vidgram',
		'porto2.png',
		'porto2_1.png',
		'Katolik Vidgram, Website Online Store yang menjual perlengkapan ibadah dan berbagai macam marchandise.',
		'0',
		'not available',
	],
	[
		'Grand Luley Manado',
		'porto3.png',
		'porto3_1.png',
		'Grand Luley Manado, Website Company Profile yang menampilkan informasi detail mengenai lokasi, biaya dan segala fasilitas yang disediakan.',
		'1',
		'https://www.luleyhotels.com/',
	],
	[
		'Farmaku',
		'porto4.png',
		'porto4_1.png',
		'Farmaku, Website Online Store penyedia obat-obatan baik ethical maupun OTC, produk perawatan kesehatan dan produk kecantikan.',
		'1',
		'https://www.farmaku.com/',
	],
	[
		'Costyle Indonesia',
		'porto5.png',
		'porto5_1.png',
		'Costyle Indonesia, Website Online Store yang menyediakan baju berkualitas baik secara material, jahitan dan kenyamanan pemakaian, namun dengan harga yang sangat bersahabat di dompet para wanita.',
		'1',
		'https://www.costyleindonesia.com/',
	],
	[
		'PT. Samudra Mitra Bersama',
		'porto6.png',
		'porto6_1.png',
		'PT. Samudra Mitra Bersama, Website Company Profile yang menampilkan informasi mengenai service penggantian suku cadang untuk mesin Mitsubishi.',
		'0',
		'not available',
	],
	[
		"Marcks' Cosmetic",
		'porto7.png',
		'porto7_1.png',
		"Marcks' Cosmetic, Website Company Profile yang menampilkan informasi mengenai produk-produk yang diproduksi oleh Marcks' Cosmetic.",
		'1',
		'https://www.marckscosmetic.co.id/',
	],
	[
		"Marcks' Venus",
		'porto8.png',
		'porto8_1.png',
		"Marcks' Venus, Website Company Profile yang menampilkan informasi mengenai brand extention dari Produk Kosmetik Marcks, yang hadir dengan rangkaian yang lebih lengkap dan lebih elegan dengan colour identifity khusus yaitu warna biru.",
		'1',
		'https://www.venuscosmetic.co.id/',
	],
	[
		'Hata Arziki',
		'porto9.png',
		'porto9_1.png',
		'Hata Arziki, Website Company Profile yang menampilkan informasi mengenai dunia pekerjaan, seperti lowongan pekerjaan, job fair dan hal lainnya seputar dunia kerja.',
		'1',
		'https://hata-arziki.com/',
	],
	[
		'BRI - E-Catalog Himbara',
		'porto10.png',
		'porto10_1.png',
		'BRI - E-Catalog Himbara, Internal Website Application yang dikhususkan untuk perbandingan pengadaan barang perbankan untuk 4 Bank BUMN indonesia yaitu, BANK BRI, BANK MANDIRI, BANK BNI dan BANK BTN.',
		'0',
		'Internal Application',
	],
	[
		'BRI - Custodian Filling System',
		'porto11.png',
		'porto11_1.png',
		'BRI - Custodian Filling System, Internal Website Application yang digunakan untuk pembentukan dan monitoring suatu dokumen.',
		'0',
		'Internal Application',
	],
	[
		'BRI - Whistle Blowing System (User)',
		'porto12.png',
		'porto12_1.png',
		'BRI - Whistle Blowing System (User), Website Application yang digunakan untuk penginputan pengaduan khusus nasabah/pegawai BRI.',
		'1',
		'https://whistleblowing-system.bri.co.id/',
	],
	[
		'BRI - Whistle Blowing System (Admin)',
		'porto13.png',
		'porto13_1.png',
		'BRI - Whistle Blowing System (Admin), Internal Website Application yang digunakan untuk monitoring inputan pengaduan dari nasabah/pegawai BRI.',
		'0',
		'Internal Application',
	],
	[
		'BRI - BRISMILE (TDR Module)',
		'porto14.png',
		'porto14_1.png',
		'BRI - BRISMILE (TDR Module), Internal Website Application yang digunakan monitoring pengajuan rekanan BRI.',
		'0',
		'Internal Application',
	],
	[
		'BRI - BRISMILE (Mapping GL Amortisasi Module)',
		'porto15.png',
		'porto15_1.png',
		'BRI - BRISMILE (Mapping GL Amortisasi Module), Internal Website Application yang digunakan untuk mapping GL AMORTISASI (Aset BRI).',
		'0',
		'Internal Application',
	],
	[
		'BRI - BRISMILE NEW (Report Aset (Dashboard & Report) Module)',
		'porto16.png',
		'porto16_1.png',
		'BRI - BRISMILE NEW (Report Aset (Dashboard & Report) Module), Internal Website Application yang digunakan untuk membuat request pelaporan aset BRI.',
		'0',
		'Internal Application',
	],
	[
		'BRI - BRISMILE NEW (Aset Sewa (PSAK 73) Module)',
		'porto17.png',
		'porto17_1.png',
		'BRI - BRISMILE NEW (Aset Sewa (PSAK 73) Module), Internal Website Application yang digunakan untuk penginputan aset sewa BRI.',
		'0',
		'Internal Application',
	],
]
